//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pandami2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class demande_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public demande_service()
        {
            this.equipement = new HashSet<equipement>();
        }
    
        public int id_demande { get; set; }
        public int id_emetteur { get; set; }
        public System.DateTime date_enregistrement { get; set; }
        public System.DateTime date_realisation { get; set; }
        public string adresse_realisation { get; set; }
        public Nullable<int> id_ville { get; set; }
        public System.TimeSpan heure_realisation { get; set; }
        public int id_type_service { get; set; }
        public Nullable<System.DateTime> date_annulation { get; set; }
        public Nullable<System.DateTime> date_cloture { get; set; }
        public Nullable<System.DateTime> date_non_finalisation { get; set; }
        public Nullable<int> id_motif_annulation { get; set; }
    
        public virtual type_service type_service { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        public virtual ville ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipement> equipement { get; set; }
    }
}
