//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pandami2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utilisateur()
        {
            this.demande_service = new HashSet<demande_service>();
        }
    
        public int id_utilisateur { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public int id_genre { get; set; }
        public System.DateTime date_naissance { get; set; }
        public string adresse { get; set; }
        public int id_ville { get; set; }
        public string num_telephone { get; set; }
        public string email { get; set; }
        public System.DateTime date_inscription { get; set; }
        public Nullable<System.DateTime> date_desinscription { get; set; }
        public Nullable<int> id_motif_desinscription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<demande_service> demande_service { get; set; }
        public virtual genre genre { get; set; }
        public virtual motif_desinscription motif_desinscription { get; set; }
        public virtual ville ville { get; set; }
    }
}
